[colors.primary]
background = '#091e35'
foreground = '#f2f2f3'
 
[colors.cursor]
text = '#f2f2f3'
cursor = '#afb2b6' 
 
[colors.vi_mode_cursor]
text = '#091e35'
cursor = '#65a4e6' 
 
[colors.search.matches]
foreground = '#0c2846' 
background = '#9b4fe3' 
 
[colors.search.focused_match]
foreground = '#0c2846' 
background = '#65a4e6' 
 
[colors.footer_bar]
foreground = '#0c2846' 
background = '#e3e5e8' 
 
[colors.hints.start]
foreground = '#0c2846' 
background = '#4f4fe3' 
 
[colors.hints.end]
foreground = '#0c2846' 
background = '#4f4fe3' 
 
[colors.selection]
text = '#091e35'
background = '#65a4e6'
 
 
[colors.normal]
black = '#181818' 
red = '#fd4663' 
green = '#65a4e6' 
yellow = '#2b64a1' 
blue = '#65a4e6' 
magenta = '#9b4fe3' 
cyan = '#4f4fe3' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 